# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./testdata
        shell: sudo --preserve-env=PATH bash -e {0}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go 1.19
        uses: actions/setup-go@v6
        with:
          go-version: "1.19"
          check-latest: true
          cache: false

      - name: Test Go 1.19
        run: |
          echo $PATH
          go version
          go test

      - name: Setup Go Stable
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
          cache: false

      - name: Test Go Stable
        run: |
          echo $PATH
          go version
          go mod edit -go $(go version | grep -Eo [0-9]+\.[0-9]+)
          go get golang.org/x/net@latest
          go test
